name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: '🔑 FE'
    labels:
      - '🔑 FE'
  - title: '🔒 BE'
    labels:
      - '🔒 BE'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
