spring:
  profiles:
    active: { DEPLOY_ACTIVE:dev }
  servlet:
    multipart:
      enabled: true

springdoc:
  swagger-ui:
    path: /funeat-api
    enabled: true
    tags-sorter: alpha

kakao:
  rest-api-key: { REST_API_KEY }
  redirect-uri: { REDIRECT_URI }
