spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: { DEV-DB-URL }
    username: { DEV-DB-USERNAME }
    password: { DEV-DB-PASSWORD }

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

review:
  image:
    path: { DEV-IMAGE-PATH }
