spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: { DEV_DB_URL }
    username: { DEV_DB_USERNAME }
    password: { DEV_DB_PASSWORD }

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

kakao:
  rest-api-key: { DEV_REST_API_KEY }
  redirect-uri: { DEV_REDIRECT_URI }
  admin-key: { DEV_ADMIN_KEY }

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, metrics, prometheus
      base-path: { ACTUATOR_BASE_PATH }
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  server:
    port: { SERVER_PORT }

cloud:
  aws:
    region:
      static: { S3_REGION }
    s3:
      bucket: { S3_BUCKET }
      folder: { S3_DEV_FOLDER }
      cloudfrontPath: { S3_DEV_CLOUDFRONT_PATH }
