spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: { PROD_DB_URL }
    username: { PROD_DB_USERNAME }
    password: { PROD_DB_PASSWORD }

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

image:
  path: { PROD_IMAGE_PATH }
