spring:
  profiles:
    active: { DEPLOY_ACTIVE }
  servlet:
    multipart:
      enabled: true
      maxFileSize: 10MB
      maxRequestSize: 15MB

springdoc:
  swagger-ui:
    path: /funeat-api
    enabled: true
    tags-sorter: alpha

logging:
  file:
    path: { LOG_DIR }

server:
  servlet:
    session:
      cookie:
        name: FUNEAT
