spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: { PROD-DB-URL }
    username: { PROD-DB-USERNAME }
    password: { PROD-DB-PASSWORD }

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

review:
  image:
    path: { PROD-IMAGE-PATH }
