spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  level:
    org.hibernate.type.descriptor.sql: trace

kakao:
  rest-api-key: { LOCAL_REST_API_KEY }
  redirect-uri: { LOCAL_REDIRECT_URI }
  admin-key: { LOCAL_ADMIN_KEY }

cloud:
  aws:
    region:
      static: { S3_REGION }
    s3:
      bucket: { S3_BUCKET }
      folder: { S3_LOCAL_FOLDER }
      cloudfrontPath: { S3_LOCAL_CLOUDFRONT_PATH }
    image:
      food: { LOCAL_BASIC_FOOD_IMAGE }
      store: { LOCAL_BASIC_STORE_IMAGE }
