spring:
  profiles:
    active: { DEPLOY_ACTIVE }
  servlet:
    multipart:
      enabled: true
      maxFileSize: 10MB
      maxRequestSize: 15MB

springdoc:
  swagger-ui:
    path: /funeat-api
    enabled: true
    tags-sorter: alpha

logging:
  file:
    path: { LOG_DIR }

server:
  tomcat:
    threads:
      max: { MAX_THREADS }
    max-connections: { MAX_CONNECTIONS }
    accept-count: { ACCEPT_COUNT }
  servlet:
    session:
      cookie:
        name: FUNEAT

back-office:
  id: { BACK_OFFICE_ID }
  key: { BACK_OFFICE_KEY }
